#!/bin/bash

# Configure Jenkins Job for Local Repository Testing

JENKINS_URL="http://localhost:8080"
JOB_NAME="club-management-pipeline"

echo "📝 Hướng dẫn cấu hình Jenkins Job với Local Repository"
echo "=============================================="
echo ""
echo "✅ Repository đã được mount vào Jenkins container tại: /workspace"
echo ""
echo "🔧 Các bước cấu hình trong Jenkins UI:"
echo ""
echo "1. Truy cập: ${JENKINS_URL}/job/${JOB_NAME}/configure"
echo ""
echo "2. Scroll xuống phần 'Pipeline' và cấu hình:"
echo ""
echo "   Definition: Pipeline script from SCM"
echo "   SCM: Git"
echo ""
echo "   Repository URL: file:///workspace"
echo "   (Repository đã được mount vào container)"
echo ""
echo "   Credentials: - none -"
echo "   (Không cần credentials cho local repository)"
echo ""
echo "   Branches to build:"
echo "   Branch Specifier: */main"
echo ""
echo "   Script Path: Jenkinsfile"
echo ""
echo "3. Scroll lên trên, tìm 'Build Triggers' và BỎ CHỌN tất cả"
echo "   (Không cần trigger tự động cho local testing)"
echo ""
echo "4. Click 'Save'"
echo ""
echo "5. Click 'Build Now' để test pipeline"
echo ""
echo "=============================================="
echo ""
echo "🌐 Mở Jenkins UI:"
open "${JENKINS_URL}/job/${JOB_NAME}/configure" 2>/dev/null || echo "   ${JENKINS_URL}/job/${JOB_NAME}/configure"
echo ""
echo "💡 Lưu ý:"
echo "   - Local repository là read-only trong container"
echo "   - Mọi thay đổi code cần commit trước khi build"
echo "   - Jenkins sẽ đọc code từ /workspace trong container"
echo ""
